name: Dev Branch deploy

on:
  push:
    branches:
      - 22-run-build-deploy-on-merge

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Build & Deploy to development branch on VIP Go
    env:
      DEPLOY_REPO: wpcomvip/wikimediafoundation-org
      DEPLOY_BRANCH: 22-run-build-deploy-on-merge-built
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: Lock PHP and composer versions
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"

      - name: Install Composer Dependencies
        uses: "ramsey/composer-install@v1"

      - name: Install npm dependencies
        uses: "bahmutov/npm-install@v1"
        with:
          working-directory: themes/shiro

      - name: Build assets
        run: (cd themes/shiro && npm run build)

      - name: Run VIP Go Deploy script
        run: ../vip-go-deploy.sh
        env:
          SRC_DIR: ${{ github.workspace }}
          TMP_DIR: ${{ runner.temp }}
          DEPLOY_REPO: humanmade/Wikimedia
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
